### PR TITLE
fixed pagination problem, refactor QueryBuilder etc...

### PR DESCRIPTION
**Pull request by p333ter**
fixed pagination problem, refactor QueryBuilder etc...

### CODE REVIEW

**Comment by mgwojciech** [comment]
Wow Mate, great job!
One question, why es2020? I'm not sure if that will work with spfx solutions. Did You get a chance to check it?

**Comment by p333ter** [comment]
Hi there, thank you. I think you brought up a great idea about the query builder 🫡
Nope, I didn't. Probably we can change it to ES6 if you wish 😎

**Comment by p333ter** [comment]
So I changed that tsconfig.json :)

**Comment by mgwojciech** [comment]
Lovely.
Great to see someone is actually finding this one useful :)

**Comment by mgwojciech** [comment]
I see there are some unit tests failing, I'll fix those tomorrow and push new version

**Comment by p333ter** [comment]
Doh...my bad.i didn't check the tests. I was just looking for new functionality 🙈

**Comment by mgwojciech** [comment]
I figured the issue with returning itemCount is related to the fact that ?$select=ItemCount returns xml while ?$select=itemCount returns json. I fixed that and have one more question ;) I see You are sending the parameters wrapped with data object (in post body) as well as the return value in Your code is expected to be wrapped in data. During my tests I did not need that at any point. Could You describe the scenario?
Or maybe I can just extract those two operations to separate method which can be overwritten in inheriting class?

**Comment by mgwojciech** [comment]
I did manual merge, I left out the "do-while" strategy for getting all items count as I think it works as expected with one call, if You want to implement it for Your case, please do it in a separate class that inherits from SPListItemCamlPagedDataProvider. The package is already published to npm.
I also added dev branch so we can collaborate there more easily :)

Once again - thanks for the great contribution!

**Pull request merged**
